# Generated by Django 4.2.1 on 2023-06-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='district_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Районы города'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='event',
            name='persons_count',
            field=models.CharField(max_length=100, null=True, verbose_name='Количество человек'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_type',
            field=models.CharField(max_length=200, null=True, verbose_name='Тип места'),
        ),
        migrations.AddField(
            model_name='event',
            name='pushkin_card',
            field=models.BooleanField(null=True, verbose_name='Пушкинская карта'),
        ),
        migrations.AddField(
            model_name='event',
            name='sales',
            field=models.BooleanField(null=True, verbose_name='Наличие акций'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Начальная дата'),
        ),
        migrations.AddField(
            model_name='event',
            name='work_hours',
            field=models.CharField(choices=[('Круглые сутки', 'Круглые сутки'), ('8-21', 'с 8:00 до 21:00'), ('21-8', 'с 21:00 до 8:00')], max_length=200, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
