# Generated by Django 4.2.1 on 2023-06-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='district_name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='pushkin_card',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sales',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='persons_count',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='place_type',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='work_hours',
            new_name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='temporary',
            field=models.BooleanField(null=True, verbose_name='Временные события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
